### ISSUE TITLE
Uses C-style comments instead of viml's "

### ISSUE THREAD

**Issue by bronson** [EvanHahn/atom-vimL#5]
When I hit `cmd-/`, the line or selection gets surrounded by C-style comments.

I'd expect the lines to be prepended with `"` characters.

**Comment by bronson** [comment]
It looks like the fix is already in...  you just haven't released it yet?

https://github.com/EvanHahn/atom-vimL/pull/4

**Comment by EvanHahn** [comment]
Whoops, you're right—just pushed version `0.3.0`. Should be fixed!

**Comment by bronson** [comment]
yep, looks good.  thanks!
