### ISSUE TITLE
Registration of interest for transfer of ownership

### ISSUE THREAD

**Issue by Alhadis** [EvanHahn/atom-vimL#6]
I was about to report a recursion error with the package's pattern-matching, when I noticed this in the repo's description:

> Abandoned. Add an issue if you want to take over!

I'd be more than happy to take care of it. =)

**Comment by EvanHahn** [comment]
Sure! Would you like me to transfer it to you?

**Comment by Alhadis** [comment]
Yes please. =) That'd be ace, I'll look after it.

**Comment by EvanHahn** [comment]
"Repository transfer to Alhadis requested", according to GitHub! Should be yours soon.

Thanks for taking it!

**Comment by Alhadis** [comment]
No problem! =) I already curate two language repos, and I'm working on a third... I may as well make it a family of four, haha.

**Comment by Alhadis** [comment]
@EvanHahn, you still need to transfer ownership of the actual package to me [on Atom.io](https://atom.io/packages/language-viml). Check Atom's docs, [they have a section about transferring ownership of a package](http://flight-manual.atom.io/behind-atom/sections/maintaining-your-packages/).

**Comment by Alhadis** [comment]
@EvanHahn, just for your reference, [I asked a question on Stack Exchange](http://opensource.stackexchange.com/q/2822) concerning this repository. I hope you're satisfied with the outcome.

**Comment by EvanHahn** [comment]
I'm happy to update the license to include you, if you'd like. Or do any other kind of "hey, this is no longer mine" commenting.

**Comment by Alhadis** [comment]
Nah, it's fine. =) To be honest, I'm less concerned with ownership than accuracy.

BTW, once I've finished migrating [Vim's syntax definitions of its own language](https://github.com/Alhadis/language-viml/blob/master/tests/vim-syntax.vim) to TextMate-compatible format, I'll probably arrange to have the grammar used for VimL highlighting on GitHub. The one they're using now is a [Sublime grammar](https://github.com/SalGnt/Sublime-VimL) that was seemingly converted from the same source, which... doesn't appear that comprehensive to begin with...
